### ISSUE TITLE
Power chosen for IDW interpolation

### ISSUE THREAD

**Issue by ricalanis** [diegovalle/hoyodesmog#6]
hey Diego! Congrats on another great project!

I was wondering how you choose the power for the IDW function to get the heat maps? As far as I understood you took 6, but some papers recommend 1 or 2 for air pollution depending on the geometry. (http://www.sciencedirect.com/science/article/pii/S009830041200372X) 

You had any reasoning behind this?

**Comment by diegovalle** [comment]
Thanks, a value of 2 does seem more reasonable
